# Generated by Django 4.2.5 on 2025-03-14 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='features',
            field=models.BooleanField(default=False),
        ),
    ]
