# Generated by Django 4.2.5 on 2025-03-14 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_features'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='features',
        ),
    ]
