# Generated by Django 4.2.5 on 2025-03-14 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('realtors', '0002_realtor_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realtor',
            name='featured',
        ),
    ]
